package de.complex.clxproductsync.monitor.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.1 in JDK 6 Generated
 * source version: 2.1
 *
 */
@WebServiceClient(name = "WsServerService", targetNamespace = "http://server.monitor.jclxwebsync.complex.de/", wsdlLocation = "http://192.168.50.104:8088/services?wsdl")
public class WsServerService
        extends Service {

    private final static URL WSSERVERSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        try {
            url = new URL("http://192.168.50.104:8088/services?wsdl");
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        WSSERVERSERVICE_WSDL_LOCATION = url;
    }

    public WsServerService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WsServerService() {
        super(WSSERVERSERVICE_WSDL_LOCATION, new QName("http://server.monitor.jclxwebsync.complex.de/", "WsServerService"));
    }

    /**
     *
     * @return returns JClxWebSyncWebServices
     */
    @WebEndpoint(name = "jClxWebSyncWebServicesPort")
    public JClxWebSyncWebServices getJClxWebSyncWebServicesPort() {
        return (JClxWebSyncWebServices) super.getPort(new QName("http://server.monitor.jclxwebsync.complex.de/", "jClxWebSyncWebServicesPort"), JClxWebSyncWebServices.class);
    }

    /**
     *
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to
     * configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns JClxWebSyncWebServices
     */
    @WebEndpoint(name = "jClxWebSyncWebServicesPort")
    public JClxWebSyncWebServices getJClxWebSyncWebServicesPort(WebServiceFeature... features) {
        return (JClxWebSyncWebServices) super.getPort(new QName("http://server.monitor.jclxwebsync.complex.de/", "jClxWebSyncWebServicesPort"), JClxWebSyncWebServices.class, features);
    }

}
