
package de.complex.clxproductsync.soap.transfer;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "TransferPort", targetNamespace = "urn:Transfer")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface TransferPort {


    /**
     * 
     * @param password
     * @param xml
     * @param login
     * @param snjobIn
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SoapAnswerList
     */
    @WebMethod(operationName = "SetDataFromXml", action = "urn:Transfer#TransferApi#SetDataFromXml")
    @WebResult(name = "SoapAnswer", partName = "SoapAnswer")
    public SoapAnswerList setDataFromXml(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "SnjobIn", partName = "SnjobIn")
        SnjobIn snjobIn,
        @WebParam(name = "xml", partName = "xml")
        String xml);

    /**
     * 
     * @param password
     * @param limit
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SnjobwebList
     */
    @WebMethod(operationName = "GetListFromSnjobweb", action = "urn:Transfer#TransferApi#GetListFromSnjobweb")
    @WebResult(name = "Snjobweb", partName = "Snjobweb")
    public SnjobwebList getListFromSnjobweb(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "limit", partName = "limit")
        int limit);

    /**
     * 
     * @param snjobwebid
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.XmlOut
     */
    @WebMethod(operationName = "GetXmlFromSnjobweb", action = "urn:Transfer#TransferApi#GetXmlFromSnjobweb")
    @WebResult(name = "XmlOut", partName = "XmlOut")
    public XmlOut getXmlFromSnjobweb(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "snjobwebid", partName = "snjobwebid")
        long snjobwebid);

    /**
     * 
     * @param snjobwebid
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SoapAnswer
     */
    @WebMethod(operationName = "SetSnjobwebOk", action = "urn:Transfer#TransferApi#SetSnjobwebOk")
    @WebResult(name = "SoapAnswer", partName = "SoapAnswer")
    public SoapAnswer setSnjobwebOk(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "snjobwebid", partName = "snjobwebid")
        long snjobwebid);

    /**
     * 
     * @param filedataIn
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SoapAnswer
     */
    @WebMethod(operationName = "SetFile", action = "urn:Transfer#TransferApi#SetFile")
    @WebResult(name = "SoapAnswer", partName = "SoapAnswer")
    public SoapAnswer setFile(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "FiledataIn", partName = "FiledataIn")
        FiledataIn filedataIn);

    /**
     * 
     * @param filedataIn
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SoapAnswer
     */
    @WebMethod(operationName = "DeleteFile", action = "urn:Transfer#TransferApi#DeleteFile")
    @WebResult(name = "SoapAnswer", partName = "SoapAnswer")
    public SoapAnswer deleteFile(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "FiledataIn", partName = "FiledataIn")
        FiledataIn filedataIn);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SoapInfoList
     */
    @WebMethod(operationName = "Info", action = "urn:Transfer#TransferApi#Info")
    @WebResult(name = "SoapInfo", partName = "SoapInfo")
    public SoapInfoList info(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param login
     * @param key
     * @return
     *     returns de.complex.clxproductsync.soap.transfer.SoapInfo
     */
    @WebMethod(operationName = "InfoByKey", action = "urn:Transfer#TransferApi#InfoByKey")
    @WebResult(name = "SoapInfo", partName = "SoapInfo")
    public SoapInfo infoByKey(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "key", partName = "key")
        String key);

}
