
package de.complex.clxproductsync.soap.transfer;

import java.net.URL;
import javax.xml.namespace.QName;
import jakarta.xml.ws.Service;
import jakarta.xml.ws.WebEndpoint;
import jakarta.xml.ws.WebServiceClient;
import jakarta.xml.ws.WebServiceException;
import jakarta.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebServiceClient(name = "TransferService", targetNamespace = "urn:Transfer", wsdlLocation = "/wsdl/transfer.wsdl")
public class TransferService
    extends Service
{

    private final static URL TRANSFERSERVICE_WSDL_LOCATION;
    private final static WebServiceException TRANSFERSERVICE_EXCEPTION;
    private final static QName TRANSFERSERVICE_QNAME = new QName("urn:Transfer", "TransferService");

    static {
        TRANSFERSERVICE_WSDL_LOCATION = de.complex.clxproductsync.soap.transfer.TransferService.class.getResource("/wsdl/transfer.wsdl");
        WebServiceException e = null;
        if (TRANSFERSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find '/wsdl/transfer.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        TRANSFERSERVICE_EXCEPTION = e;
    }

    public TransferService() {
        super(__getWsdlLocation(), TRANSFERSERVICE_QNAME);
    }

    public TransferService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TRANSFERSERVICE_QNAME, features);
    }

    public TransferService(URL wsdlLocation) {
        super(wsdlLocation, TRANSFERSERVICE_QNAME);
    }

    public TransferService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TRANSFERSERVICE_QNAME, features);
    }

    public TransferService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TransferService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TransferPort
     */
    @WebEndpoint(name = "TransferPort")
    public TransferPort getTransferPort() {
        return super.getPort(new QName("urn:Transfer", "TransferPort"), TransferPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link jakarta.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TransferPort
     */
    @WebEndpoint(name = "TransferPort")
    public TransferPort getTransferPort(WebServiceFeature... features) {
        return super.getPort(new QName("urn:Transfer", "TransferPort"), TransferPort.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TRANSFERSERVICE_EXCEPTION!= null) {
            throw TRANSFERSERVICE_EXCEPTION;
        }
        return TRANSFERSERVICE_WSDL_LOCATION;
    }

}
