
package de.complex.clxproductsync.soap.datacheck;

import jakarta.jws.WebMethod;
import jakarta.jws.WebParam;
import jakarta.jws.WebResult;
import jakarta.jws.WebService;
import jakarta.jws.soap.SOAPBinding;
import jakarta.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 3.0.1
 * Generated source version: 3.0
 * 
 */
@WebService(name = "DatacheckPort", targetNamespace = "urn:Datacheck")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface DatacheckPort {


    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.datacheck.SpoolcheckList
     */
    @WebMethod(operationName = "GetSpoolcheck", action = "urn:Datacheck#DatacheckApi#GetSpoolcheck")
    @WebResult(name = "Spoolcheck", partName = "Spoolcheck")
    public SpoolcheckList getSpoolcheck(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.datacheck.SpoolcheckList
     */
    @WebMethod(operationName = "GetSpoolcheckList", action = "urn:Datacheck#DatacheckApi#GetSpoolcheckList")
    @WebResult(name = "Spoolcheck", partName = "Spoolcheck")
    public SpoolcheckList getSpoolcheckList(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.datacheck.SpoolcheckList
     */
    @WebMethod(operationName = "GetSnjobwebList", action = "urn:Datacheck#DatacheckApi#GetSnjobwebList")
    @WebResult(name = "Spoolcheck", partName = "Spoolcheck")
    public SpoolcheckList getSnjobwebList(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param login
     * @return
     *     returns de.complex.clxproductsync.soap.datacheck.SpoolcheckList
     */
    @WebMethod(operationName = "GetWebSpoolcheckList", action = "urn:Datacheck#DatacheckApi#GetWebSpoolcheckList")
    @WebResult(name = "Spoolcheck", partName = "Spoolcheck")
    public SpoolcheckList getWebSpoolcheckList(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password);

    /**
     * 
     * @param password
     * @param spoolcheck
     * @param login
     */
    @WebMethod(operationName = "SetSpoolcheckList", action = "urn:Datacheck#DatacheckApi#SetSpoolcheckList")
    public void setSpoolcheckList(
        @WebParam(name = "login", partName = "login")
        String login,
        @WebParam(name = "password", partName = "password")
        String password,
        @WebParam(name = "Spoolcheck", partName = "Spoolcheck")
        SpoolcheckList spoolcheck);

}
